apiVersion: v1
kind: Secret
metadata:
  name: myapp-secret
type: Opaque # different types of secrets exist, this on is for arbitrary user-defined data
data:
  username: bXl1c2Vy # value has to be base64 encoded
  password: Ym9icg==
