apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template: # template for the pods
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
        - name: log-sidecar
          image: busybox:1.28
          command: ["sh", "-c"]
          args:
            - while true; do
                echo sync app logs;
                printenv POD_NAME POD_SERVICE_ACCOUNT POD_IP;
                sleep 20;
              done;
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name #get value from pod config metadata.name
            - name: POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName #get value from pod config spec.serviceAccountName
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP #get value from pod config status.podIP
      initContainers:
        - name: mydb-available
          image: busybox:1.28
          command: ["sh", "-c", "until nslookup mydb-service; do echo waiting for mydb; sleep 4; done"] #waits for mydb-service to be available

