apiVersion: v1
kind: ServiceAccount
metadata:
  name: myscript
---
apiVersion: v1
kind: Secret
metadata:
  name: myscript-token
  annotations:
    kubernetes.io/service-account.name: myscript
type: kubernetes.io/service-account-token

