apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cicd-role
  #normal role always limited to namespace, if left out it is the default one
  #namespace: my-app
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - create
      - update
      - list
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create
      - update
      - list
