apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dev-cr
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
    verbs: ["*"] # allow all
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulSets
    verbs:
      - get
      - list
      - create
