apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
spec:
  containers:
    - image: busybox
      name: busybox
#      command: ["printenv"]
#      args: ["HOSTNAME", "KUBERNETES_PORT"]
      command: ["sh", "-c", "sleep 1000"]
      args: []
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
