apiVersion: v1
kind: Pod
metadata:
  name: nginx-node-affinity
spec:
  containers:
    - name: myapp
      image: busybox:1.28
  affinity:
    nodeAffinity:
      # must be linux os
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                  - linux
      # cpu type is preferred
      preferredDuringSchedulingIgnoredDuringExecution:
        - preference:
            matchExpressions:
              - key: type
                operator: In
                values:
                  - cpu
          weight: 1
